strip out removing source code

diff --git a/codecov b/codecov
--- a/codecov
+++ b/codecov
@@ -118,18 +118,8 @@ swiftcov() {
       then
         say "    $g+$x Building reports for $_proj $_type"
         _proj_name=$(echo "$_proj" | sed -e 's/[[:space:]]//g')
-        while IFS="$(printf '\n\t ')" read -r line;
-        do
-          if [ -z "$line" ]; then : # [skip] empty line
-          elif [[ "$line" == '|'* ]]; then : # [skip] irrelvent data
-          elif [[ "$line" == '-'* ]]; then : # [skip] irrelvent data
-          elif [[ "$line" == '/'* ]]; then # file name
-            echo "$line"
-          else # coverage data: remove source from file
-            echo "${line%|*}"
-          fi
-        done < <(xcrun llvm-cov show -instr-profile "$1" "$f/$_proj") >> "$_proj_name.$_type.coverage.txt" \
-             || echo "    ${r}**>${x} llvm-cov failed to produce results for $f/$_proj"
+        xcrun llvm-cov show -instr-profile "$1" "$f/$_proj" > "$_proj_name.$_type.coverage.txt" \
+          || echo "    ${r}**>${x} llvm-cov failed to produce results for $f/$_proj"
       fi
     done
   done
